#
# Title: Hashing
# Author: Ferhat Korkmaz
# ID: 21901940
# Assignment: 4
#
hw4 : main.o HashTable.o
	g++ -std=c++11 main.o HashTable.o -o hw4

main.o : main.cpp
	g++ -std=c++11 -c main.cpp

HashTable.o : HashTable.cpp HashTable.h
	g++ -std=c++11 -c HashTable.cpp
